services:
    # Allows "FEATURE_*" as role names.
    matthimatiker_feature_flag.feature_voter:
        class: "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\RoleHierarchyVoter"
        arguments:
            - "@security.role_hierarchy"
            - "FEATURE_"
        public: false
        tags:
            - { name: security.voter }

    # Allows using the IS_AUTHENTICATED_* permissions in the role hierarchy.
    matthimatiker_feature_flag.role_hierarchy.authentication_aware_role_hierarchy:
        class: "Matthimatiker\\FeatureFlagBundle\\Security\\AuthenticationAwareRoleHierarchy"
        decorates: "security.role_hierarchy"
        arguments:
            - "@matthimatiker_feature_flag.role_hierarchy.authentication_aware_role_hierarchy.inner"
            - "@matthimatiker_feature_flag.role_hierarchy.authorization_checker"
        public: false

    matthimatiker_feature_flag.role_hierarchy.authorization_checker:
        class: "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationChecker"
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
            - "@matthimatiker_feature_flag.role_hierarchy.decision_manager"
            - "%security.access.always_authenticate_before_granting%"
        public: false

    matthimatiker_feature_flag.role_hierarchy.decision_manager:
        class: "Symfony\\Component\\Security\\Core\\Authorization\\AccessDecisionManager"
        arguments:
            -
                - "@security.access.authenticated_voter"
        public: false

    # Adds special roles for guests that can be used to assign features that are not available
    # to logged in users.
    matthimatiker_feature_flag.guest_roles.authentication_provider:
        class: "Matthimatiker\\FeatureFlagBundle\\Security\\AdditionalAnonymousRolesAuthenticationProvider"
        abstract: true
        arguments:
            # The first argument is the replaced provider; it will be injected by the bundle extension.
            - ~
            - ["ROLE_ANONYMOUS"]
        public: false
